### ISSUE TITLE
Optionally accept TCPListener rather than ToSocketAddrs

### ISSUE THREAD

**Issue by bobrik** [tiny-http/tiny-http#164]
With `TCPListener` it's possible to [`listenfd`](https://github.com/mitsuhiko/rust-listenfd) and socket activation from systemd.

This allows to hide services into network namespaces and disallow them to do `bind` and `listen`, which is very handy security-wise. Not only can one disallow these, it's also probably possible to use `RestrictAddressFamilies` and disable even `AF_INET` and `AF_INET6` for even more through lockdown.

I'm not really sure how to make this work without breaking backward compatibility or introducing something like `_with_listener` variants for methods that require `ToSocketAddrs` today.

**Comment by Kixunil** [comment]
I need this and willing to submit a PR. Is it required to be backwards compatible? because if not, changing `server_addr` method to return `Option<SocketAddr>` might be cleaner. If it needs to be backwards compatible, then `from_tcp_listener` could also require socketaddr (which the caller could set to any value, perhaps by inspecting the socket).

**Comment by Kixunil** [comment]
Turns out it was incredibly easy to do, see PR. :)
