### ISSUE TITLE
slate release

### ISSUE THREAD

**Issue by drahnr** [tiny-http/tiny-http#169]
The last release is over a year old, and particularly #151 is a good addition for those using it besides a lot of other changes

**Comment by frewsxcv** [comment]
0.7.0 was just released!

**Comment by glandium** [comment]
Is there a specific reason this was released as 0.7.0 rather than 0.6.3? At quick glance, I don't see differences between 0.6.2 and 0.7.0 that would need a semver bump, but I could be wrong. It is an unfortunate bump, because rouille, which hasn't been updated in a while, is still on 0.6, and can't get the fix for #151.
